baseURL = 'https://tab-art-lab.github.io/'
languageCode = 'en-us'
title = 'Tab Art Lab'
theme = "masonry"

[params]
    showFooter = false

[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Tags"
    pre = "tag"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    name = "About"
    pre = "about"
    url = "/about"
    weight = 3

